---
- hosts: localhost
  tasks:
  - name: ubuntu/debian - require git, mercurial and subversion
    apt:
      package:
      - git
      - mercurial
      - subversion
    when: ansible_os_family == "Debian"
  - name: fedora - require git, mercurial and subversion
    yum:
      name:
      - git
      - mercurial
      - subversion
    when: ansible_os_family == "RedHat"

