---
- hosts: localhost
  vars:
    common_packages:  # these have the same name on all systems
     - git
     - mercurial
     - subversion
  tasks:
  # --- install software
  - name: ubuntu/debian - require git, mercurial and subversion
    apt: pkg={{ item }}
    with_items: "{{ common_packages }}"
    when: ansible_os_family == "Debian"

  - name: fedora - require git, mercurial and subversion
    yum: name={{ item }}
    with_items: "{{ common_packages }}"
    when: ansible_os_family == "RedHat"

