---
- hosts: localhost
  vars:
    common_packages:  # these have the same name on all systems
     - git
     - mercurial
     - subversion
    debian_packages:  # names spacific for Ubuntu/Debian
     - mercurial-git
    redhat_packages:  # names from RedHat/Fedora
     - hg-git

  tasks:
  # --- install software
  - name: ubuntu/debian - require git, mercurial and subversion
    apt: pkg={{ item }}
    with_items: "{{ common_packages + debian_packages }}"
    when: ansible_os_family == "Debian"

  - name: fedora - require git, mercurial and subversion
    yum: name={{ item }}
    with_items: "{{ common_packages + redhat_packages }}"
    when: ansible_os_family == "RedHat"

